image: node:12

cache:
  paths:
    - node_modules/

script:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist
    untracked: false
    expire_in: 30 days
  when: manual

pages:
  stage: deploy
  artifacts:
    paths:
      - public
  script:
    - mv dist public
  when: manual