build_pwa:
  environment: production
  stage: build
  image: node:18
  script:
    - npm install
    - npm run build -- --public-url "/app"
  artifacts:
    paths:
      - dist
    expire_in: 2 hours
  rules:
    - if: $CI_COMMIT_TAG

pages:
  environment: production
  stage: deploy
  image: busybox
  artifacts:
    paths:
      - public
  script:
    - mv dist public
    - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\)$' -exec gzip -f -k {} \;
    - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\)$' -exec brotli -f -k {} \;
  rules:
    - if: $CI_COMMIT_TAG