image: node:12

cache:
  paths:
    - node_modules/

script:
  stage: build
  script:
    - npm install
    - npm run build
  when: manual

pages:
  stage: deploy
  artifacts:
    paths:
      - public
  script:
    - mv build public
  when: manual