build:
  image: node:12
  stage: build
  script:
    - npm install
    - npm run build -- --public-url "/app"
  artifacts:
    paths:
      - dist
    untracked: false
    expire_in: 2 hours
  when: manual

pages:
  image: busybox
  stage: deploy
  artifacts:
    paths:
      - public
  script:
    - mv dist public
  when: manual